org: jeanmiraval
service: api-alumnos-rds-v2

provider:
  name: aws
  runtime: python3.13
  memorySize: 1024
  timeout: 20
  iam:
    role: arn:aws:iam::890668988889:role/LabRole
  environment:
    SECRET_NAME: /rds_mysql_alumnos/credentials
    DB_NAME: ${sls:stage}
    STAGE: ${sls:stage}

functions:
  listar:
    handler: ListarAlumnos.lambda_handler
    package:
      include:
        - ./**
    events:
      - http:
          path: /alumnos/listar
          method: get
          cors: true
          integration: lambda
